[package]
name = "dollhouse"
description = "A safe & encrypted place to share files"
repository = "https://github.com/Blooym/dollhouse"
authors = ["Blooym"]
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0.97"
axum = { version = "0.8.3", features = ["http2", "macros", "multipart"] }
axum-extra = { version = "0.10.1", features = ["typed-header"] }
blake3 = { version = "1.7.0", features = ["zeroize", "rayon"] }
bytesize = "2.0.1"
clap = { version = "4.5.34", features = ["derive", "env", "string"] }
chacha20poly1305 = "0.10.1"
clap-duration = "0.1.11"
dirs = "6.0.0"
dotenvy = "0.15.7"
duration-human = "0.1.10"
hex = "0.4.3"
infer = "0.19.0"
mime_guess = "2.0.5"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
] }
tower-http = { version = "0.6.2", features = [
    "catch-panic",
    "normalize-path",
    "timeout",
    "trace",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
rand = "0.9.0"
