services:
  dollshare:
    container_name: dollshare
    build: .
    restart: unless-stopped
    ports:
      - 8731:8731
    volumes:
      - dollshare-data:/srv/dollshare

volumes:
  dollshare-data: