services:
  dollhouse:
    container_name: dollhouse
    build: .
    restart: unless-stopped
    ports:
      - 8731:8731
    volumes:
      - dollhouse-data:/srv/dollhouse

volumes:
  dollhouse-data: